[package]
name = "fux_delaunay_c_api_tester"
version = "0.1.0"
authors = ["Olek <ntszar@gmail.com>"]
build = "build.rs"

[dependencies]
fux_delaunay = { path = "../" }

[build-dependencies]
gcc = "*"
